macro(link_openssl TARGET_NAME)
  if(IS_LINUX)
    find_package(OpenSSL REQUIRED)
    target_include_directories(${TARGET_NAME} PUBLIC ${OPENSSL_INCLUDE_DIR})
    target_link_libraries(${TARGET_NAME} PUBLIC OpenSSL::Crypto)
  endif()
endmacro()
